cc_binary(
    name = "ipc",
    srcs = ["ipc.cpp"],
    linkopts = ["-pthread"],
    deps = [
        "//lib:pbus-lib"
    ],
)

cc_binary(
    name = "packet_debug",
    srcs = ["packet_debug.cpp"],
    linkopts = ["-pthread"],
    deps = [
        "//lib:pbus-lib"
    ],
)