cc_library(
    name = "pbus-lib",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/ipc:pbus-ipc",
        "//lib/packet:pbus-packet",
        "//lib/logging:pbus-logging"
    ],
)